# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'page_game.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1473, 948)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lbl_player = QLabel(self.centralwidget)
        self.lbl_player.setObjectName(u"lbl_player")
        self.lbl_player.setGeometry(QRect(260, 350, 91, 81))
        self.lbl_player.setPixmap(QPixmap(u"../images/character_bottom_5.png"))
        self.lbl_player.setScaledContents(True)
        self.lst_slot_1 = QListWidget(self.centralwidget)
        self.lst_slot_1.setObjectName(u"lst_slot_1")
        self.lst_slot_1.setGeometry(QRect(750, 820, 111, 111))
        font = QFont()
        font.setPointSize(9)
        self.lst_slot_1.setFont(font)
        self.lst_slot_2 = QListWidget(self.centralwidget)
        self.lst_slot_2.setObjectName(u"lst_slot_2")
        self.lst_slot_2.setGeometry(QRect(870, 820, 111, 111))
        self.lst_slot_3 = QListWidget(self.centralwidget)
        self.lst_slot_3.setObjectName(u"lst_slot_3")
        self.lst_slot_3.setGeometry(QRect(990, 820, 111, 111))
        self.lst_slot_4 = QListWidget(self.centralwidget)
        self.lst_slot_4.setObjectName(u"lst_slot_4")
        self.lst_slot_4.setGeometry(QRect(1110, 820, 111, 111))
        self.lst_slot_5 = QListWidget(self.centralwidget)
        self.lst_slot_5.setObjectName(u"lst_slot_5")
        self.lst_slot_5.setGeometry(QRect(1230, 820, 111, 111))
        self.lst_slot_trash = QListWidget(self.centralwidget)
        self.lst_slot_trash.setObjectName(u"lst_slot_trash")
        self.lst_slot_trash.setGeometry(QRect(1350, 820, 111, 111))
        self.lst_slot_song1 = QListWidget(self.centralwidget)
        self.lst_slot_song1.setObjectName(u"lst_slot_song1")
        self.lst_slot_song1.setGeometry(QRect(930, 580, 111, 111))
        self.lst_slot_song2 = QListWidget(self.centralwidget)
        self.lst_slot_song2.setObjectName(u"lst_slot_song2")
        self.lst_slot_song2.setGeometry(QRect(1050, 580, 111, 111))
        self.lst_slot_song3 = QListWidget(self.centralwidget)
        self.lst_slot_song3.setObjectName(u"lst_slot_song3")
        self.lst_slot_song3.setGeometry(QRect(1170, 580, 111, 111))
        self.lst_slot_melee = QListWidget(self.centralwidget)
        self.lst_slot_melee.setObjectName(u"lst_slot_melee")
        self.lst_slot_melee.setGeometry(QRect(810, 700, 111, 111))
        self.lst_slot_ranged = QListWidget(self.centralwidget)
        self.lst_slot_ranged.setObjectName(u"lst_slot_ranged")
        self.lst_slot_ranged.setGeometry(QRect(930, 700, 111, 111))
        self.lbl_backround = QLabel(self.centralwidget)
        self.lbl_backround.setObjectName(u"lbl_backround")
        self.lbl_backround.setGeometry(QRect(-10, 0, 1491, 961))
        self.lbl_backround.setPixmap(QPixmap(u"../images/grass_backround.png"))
        self.lbl_backround.setScaledContents(True)
        self.lbl_backround.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_weapon_1 = QLabel(self.centralwidget)
        self.lbl_weapon_1.setObjectName(u"lbl_weapon_1")
        self.lbl_weapon_1.setGeometry(QRect(270, 300, 71, 31))
        self.lbl_weapon_1.setScaledContents(True)
        self.lbl_weapon_2 = QLabel(self.centralwidget)
        self.lbl_weapon_2.setObjectName(u"lbl_weapon_2")
        self.lbl_weapon_2.setGeometry(QRect(350, 320, 51, 31))
        self.lbl_weapon_2.setScaledContents(True)
        self.lbl_weapon_8 = QLabel(self.centralwidget)
        self.lbl_weapon_8.setObjectName(u"lbl_weapon_8")
        self.lbl_weapon_8.setGeometry(QRect(210, 320, 51, 31))
        self.lbl_weapon_8.setScaledContents(True)
        self.lbl_weapon_7 = QLabel(self.centralwidget)
        self.lbl_weapon_7.setObjectName(u"lbl_weapon_7")
        self.lbl_weapon_7.setGeometry(QRect(210, 370, 41, 71))
        self.lbl_weapon_7.setScaledContents(True)
        self.lbl_weapon_6 = QLabel(self.centralwidget)
        self.lbl_weapon_6.setObjectName(u"lbl_weapon_6")
        self.lbl_weapon_6.setGeometry(QRect(210, 440, 61, 31))
        self.lbl_weapon_6.setScaledContents(True)
        self.lbl_weapon_3 = QLabel(self.centralwidget)
        self.lbl_weapon_3.setObjectName(u"lbl_weapon_3")
        self.lbl_weapon_3.setGeometry(QRect(360, 370, 41, 71))
        self.lbl_weapon_3.setScaledContents(True)
        self.lbl_weapon_4 = QLabel(self.centralwidget)
        self.lbl_weapon_4.setObjectName(u"lbl_weapon_4")
        self.lbl_weapon_4.setGeometry(QRect(350, 440, 51, 31))
        self.lbl_weapon_4.setScaledContents(True)
        self.lbl_weapon_5 = QLabel(self.centralwidget)
        self.lbl_weapon_5.setObjectName(u"lbl_weapon_5")
        self.lbl_weapon_5.setGeometry(QRect(270, 450, 71, 31))
        self.lbl_weapon_5.setScaledContents(True)
        self.lbl_healthbar = QLabel(self.centralwidget)
        self.lbl_healthbar.setObjectName(u"lbl_healthbar")
        self.lbl_healthbar.setGeometry(QRect(40, 890, 400, 41))
        self.lbl_healthbar.setStyleSheet(u"background-color: rgb(255, 0, 0)")
        self.lbl_healthbarbg = QLabel(self.centralwidget)
        self.lbl_healthbarbg.setObjectName(u"lbl_healthbarbg")
        self.lbl_healthbarbg.setGeometry(QRect(37, 887, 406, 47))
        self.lbl_healthbarbg.setMaximumSize(QSize(500, 48))
        self.lbl_healthbarbg.setStyleSheet(u"background-color: rgb(255, 255, 255); border: 3px solid #000000")
        self.lbl_heartnobg = QLabel(self.centralwidget)
        self.lbl_heartnobg.setObjectName(u"lbl_heartnobg")
        self.lbl_heartnobg.setGeometry(QRect(-20, 880, 141, 61))
        self.lbl_heartnobg.setPixmap(QPixmap(u"../images/heartnobg.png"))
        self.lbl_heartnobg.setScaledContents(True)
        self.lbl_playerhealth = QLabel(self.centralwidget)
        self.lbl_playerhealth.setObjectName(u"lbl_playerhealth")
        self.lbl_playerhealth.setGeometry(QRect(27, 880, 51, 51))
        font1 = QFont()
        font1.setPointSize(20)
        self.lbl_playerhealth.setFont(font1)
        self.lbl_playerhealth.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lst_slot_armor = QListWidget(self.centralwidget)
        self.lst_slot_armor.setObjectName(u"lst_slot_armor")
        self.lst_slot_armor.setGeometry(QRect(1050, 700, 111, 111))
        self.lbl_bowability = QLabel(self.centralwidget)
        self.lbl_bowability.setObjectName(u"lbl_bowability")
        self.lbl_bowability.setGeometry(QRect(450, 880, 51, 51))
        self.lbl_bowability.setPixmap(QPixmap(u"../images/bow_ability.png"))
        self.lbl_bowability.setScaledContents(True)
        self.lbl_bowcooldown = QLabel(self.centralwidget)
        self.lbl_bowcooldown.setObjectName(u"lbl_bowcooldown")
        self.lbl_bowcooldown.setGeometry(QRect(450, 880, 51, 51))
        font2 = QFont()
        font2.setPointSize(20)
        font2.setBold(True)
        self.lbl_bowcooldown.setFont(font2)
        self.lbl_bowcooldown.setStyleSheet(u"")
        self.lbl_bowcooldown.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_wavename = QLabel(self.centralwidget)
        self.lbl_wavename.setObjectName(u"lbl_wavename")
        self.lbl_wavename.setGeometry(QRect(10, 10, 151, 81))
        font3 = QFont()
        font3.setPointSize(40)
        self.lbl_wavename.setFont(font3)
        self.lbl_wave = QLabel(self.centralwidget)
        self.lbl_wave.setObjectName(u"lbl_wave")
        self.lbl_wave.setGeometry(QRect(150, 10, 61, 81))
        self.lbl_wave.setFont(font3)
        self.lbl_wave.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_wavename_2 = QLabel(self.centralwidget)
        self.lbl_wavename_2.setObjectName(u"lbl_wavename_2")
        self.lbl_wavename_2.setGeometry(QRect(210, 10, 101, 81))
        self.lbl_wavename_2.setFont(font3)
        self.lbl_scorename = QLabel(self.centralwidget)
        self.lbl_scorename.setObjectName(u"lbl_scorename")
        self.lbl_scorename.setGeometry(QRect(1010, 10, 141, 81))
        self.lbl_scorename.setFont(font3)
        self.lbl_score = QLabel(self.centralwidget)
        self.lbl_score.setObjectName(u"lbl_score")
        self.lbl_score.setGeometry(QRect(1160, 10, 301, 81))
        self.lbl_score.setFont(font3)
        self.lbl_yapyapyap = QLabel(self.centralwidget)
        self.lbl_yapyapyap.setObjectName(u"lbl_yapyapyap")
        self.lbl_yapyapyap.setGeometry(QRect(300, 10, 701, 121))
        self.lbl_yapyapyap.setStyleSheet(u"background-color: rgb(255, 255, 255); border: 3px solid #000000")
        self.lbl_yapyapyap.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_bosshealthbar = QLabel(self.centralwidget)
        self.lbl_bosshealthbar.setObjectName(u"lbl_bosshealthbar")
        self.lbl_bosshealthbar.setGeometry(QRect(350, 30, 600, 41))
        self.lbl_bosshealthbar.setStyleSheet(u"background-color: rgb(255, 0, 0)")
        self.lbl_bossheartnobg = QLabel(self.centralwidget)
        self.lbl_bossheartnobg.setObjectName(u"lbl_bossheartnobg")
        self.lbl_bossheartnobg.setGeometry(QRect(280, 18, 141, 61))
        self.lbl_bossheartnobg.setPixmap(QPixmap(u"../images/heartnobg.png"))
        self.lbl_bossheartnobg.setScaledContents(True)
        self.lbl_bosshealth = QLabel(self.centralwidget)
        self.lbl_bosshealth.setObjectName(u"lbl_bosshealth")
        self.lbl_bosshealth.setGeometry(QRect(327, 18, 51, 51))
        self.lbl_bosshealth.setFont(font1)
        self.lbl_bosshealth.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lbl_bosshealthbarbg = QLabel(self.centralwidget)
        self.lbl_bosshealthbarbg.setObjectName(u"lbl_bosshealthbarbg")
        self.lbl_bosshealthbarbg.setGeometry(QRect(347, 27, 606, 47))
        self.lbl_bosshealthbarbg.setStyleSheet(u"background-color: rgb(255, 255, 255); border: 3px solid #000000")
        self.lbl_bossname = QLabel(self.centralwidget)
        self.lbl_bossname.setObjectName(u"lbl_bossname")
        self.lbl_bossname.setGeometry(QRect(360, 70, 411, 41))
        self.lbl_bossname.setFont(font1)
        self.lst_slot_boots = QListWidget(self.centralwidget)
        self.lst_slot_boots.setObjectName(u"lst_slot_boots")
        self.lst_slot_boots.setGeometry(QRect(1170, 700, 111, 111))
        self.lst_slot_lifeforce = QListWidget(self.centralwidget)
        self.lst_slot_lifeforce.setObjectName(u"lst_slot_lifeforce")
        self.lst_slot_lifeforce.setGeometry(QRect(1290, 700, 111, 111))
        self.lbl_choice1_backround = QLabel(self.centralwidget)
        self.lbl_choice1_backround.setObjectName(u"lbl_choice1_backround")
        self.lbl_choice1_backround.setGeometry(QRect(60, 90, 331, 811))
        self.lbl_choice1_backround.setStyleSheet(u"background-color: rgb(176, 176, 176);")
        self.lbl_choice1_title = QLabel(self.centralwidget)
        self.lbl_choice1_title.setObjectName(u"lbl_choice1_title")
        self.lbl_choice1_title.setGeometry(QRect(70, 100, 311, 71))
        self.lbl_choice1_title.setFont(font3)
        self.lbl_choice1_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_choice1_image = QLabel(self.centralwidget)
        self.lbl_choice1_image.setObjectName(u"lbl_choice1_image")
        self.lbl_choice1_image.setGeometry(QRect(70, 180, 311, 321))
        self.lbl_choice1_image.setPixmap(QPixmap(u"../images/wooden_sword_base.gif"))
        self.lbl_choice1_image.setScaledContents(True)
        self.lbl_choice1_description = QLabel(self.centralwidget)
        self.lbl_choice1_description.setObjectName(u"lbl_choice1_description")
        self.lbl_choice1_description.setGeometry(QRect(70, 510, 311, 251))
        self.lbl_choice1_description.setFont(font1)
        self.lbl_choice1_description.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_choice1 = QPushButton(self.centralwidget)
        self.btn_choice1.setObjectName(u"btn_choice1")
        self.btn_choice1.setGeometry(QRect(70, 770, 311, 121))
        self.btn_choice1.setFont(font3)
        self.btn_choice1.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.lbl_choice2_backround = QLabel(self.centralwidget)
        self.lbl_choice2_backround.setObjectName(u"lbl_choice2_backround")
        self.lbl_choice2_backround.setGeometry(QRect(580, 90, 331, 811))
        self.lbl_choice2_backround.setStyleSheet(u"background-color: rgb(176, 176, 176);")
        self.lbl_choice2_title = QLabel(self.centralwidget)
        self.lbl_choice2_title.setObjectName(u"lbl_choice2_title")
        self.lbl_choice2_title.setGeometry(QRect(590, 100, 311, 71))
        self.lbl_choice2_title.setFont(font3)
        self.lbl_choice2_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_choice2 = QPushButton(self.centralwidget)
        self.btn_choice2.setObjectName(u"btn_choice2")
        self.btn_choice2.setGeometry(QRect(590, 770, 311, 121))
        self.btn_choice2.setFont(font3)
        self.btn_choice2.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.lbl_choice2_description = QLabel(self.centralwidget)
        self.lbl_choice2_description.setObjectName(u"lbl_choice2_description")
        self.lbl_choice2_description.setGeometry(QRect(590, 510, 311, 251))
        self.lbl_choice2_description.setFont(font1)
        self.lbl_choice2_description.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_choice2_image = QLabel(self.centralwidget)
        self.lbl_choice2_image.setObjectName(u"lbl_choice2_image")
        self.lbl_choice2_image.setGeometry(QRect(590, 180, 311, 321))
        self.lbl_choice2_image.setPixmap(QPixmap(u"../images/wooden_sword_base.gif"))
        self.lbl_choice2_image.setScaledContents(True)
        self.lbl_choice3_backround = QLabel(self.centralwidget)
        self.lbl_choice3_backround.setObjectName(u"lbl_choice3_backround")
        self.lbl_choice3_backround.setGeometry(QRect(1100, 90, 331, 811))
        self.lbl_choice3_backround.setStyleSheet(u"background-color: rgb(176, 176, 176);")
        self.lbl_choice3_title = QLabel(self.centralwidget)
        self.lbl_choice3_title.setObjectName(u"lbl_choice3_title")
        self.lbl_choice3_title.setGeometry(QRect(1110, 100, 311, 71))
        self.lbl_choice3_title.setFont(font3)
        self.lbl_choice3_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_choice3 = QPushButton(self.centralwidget)
        self.btn_choice3.setObjectName(u"btn_choice3")
        self.btn_choice3.setGeometry(QRect(1110, 770, 311, 121))
        self.btn_choice3.setFont(font3)
        self.btn_choice3.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.lbl_choice3_description = QLabel(self.centralwidget)
        self.lbl_choice3_description.setObjectName(u"lbl_choice3_description")
        self.lbl_choice3_description.setGeometry(QRect(1110, 510, 311, 251))
        self.lbl_choice3_description.setFont(font1)
        self.lbl_choice3_description.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_choice3_image = QLabel(self.centralwidget)
        self.lbl_choice3_image.setObjectName(u"lbl_choice3_image")
        self.lbl_choice3_image.setGeometry(QRect(1110, 180, 311, 321))
        self.lbl_choice3_image.setPixmap(QPixmap(u"../images/wooden_sword_base.gif"))
        self.lbl_choice3_image.setScaledContents(True)
        self.lbl_melee = QLabel(self.centralwidget)
        self.lbl_melee.setObjectName(u"lbl_melee")
        self.lbl_melee.setGeometry(QRect(810, 790, 111, 20))
        font4 = QFont()
        font4.setBold(True)
        self.lbl_melee.setFont(font4)
        self.lbl_melee.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_ranged = QLabel(self.centralwidget)
        self.lbl_ranged.setObjectName(u"lbl_ranged")
        self.lbl_ranged.setGeometry(QRect(930, 790, 111, 20))
        self.lbl_ranged.setFont(font4)
        self.lbl_ranged.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_armor = QLabel(self.centralwidget)
        self.lbl_armor.setObjectName(u"lbl_armor")
        self.lbl_armor.setGeometry(QRect(1050, 790, 111, 20))
        self.lbl_armor.setFont(font4)
        self.lbl_armor.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_boots = QLabel(self.centralwidget)
        self.lbl_boots.setObjectName(u"lbl_boots")
        self.lbl_boots.setGeometry(QRect(1170, 790, 111, 20))
        self.lbl_boots.setFont(font4)
        self.lbl_boots.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_lifeforce = QLabel(self.centralwidget)
        self.lbl_lifeforce.setObjectName(u"lbl_lifeforce")
        self.lbl_lifeforce.setGeometry(QRect(1290, 790, 111, 20))
        self.lbl_lifeforce.setFont(font4)
        self.lbl_lifeforce.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_disc1 = QLabel(self.centralwidget)
        self.lbl_disc1.setObjectName(u"lbl_disc1")
        self.lbl_disc1.setGeometry(QRect(930, 670, 111, 20))
        self.lbl_disc1.setFont(font4)
        self.lbl_disc1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_disc2 = QLabel(self.centralwidget)
        self.lbl_disc2.setObjectName(u"lbl_disc2")
        self.lbl_disc2.setGeometry(QRect(1050, 670, 111, 20))
        self.lbl_disc2.setFont(font4)
        self.lbl_disc2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_disc3 = QLabel(self.centralwidget)
        self.lbl_disc3.setObjectName(u"lbl_disc3")
        self.lbl_disc3.setGeometry(QRect(1170, 670, 111, 20))
        self.lbl_disc3.setFont(font4)
        self.lbl_disc3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_backinblackability = QLabel(self.centralwidget)
        self.lbl_backinblackability.setObjectName(u"lbl_backinblackability")
        self.lbl_backinblackability.setGeometry(QRect(510, 880, 51, 51))
        self.lbl_backinblackability.setPixmap(QPixmap(u"../images/backinblack.png"))
        self.lbl_backinblackability.setScaledContents(True)
        self.lbl_backinblackcooldown = QLabel(self.centralwidget)
        self.lbl_backinblackcooldown.setObjectName(u"lbl_backinblackcooldown")
        self.lbl_backinblackcooldown.setGeometry(QRect(510, 880, 51, 51))
        self.lbl_backinblackcooldown.setFont(font2)
        self.lbl_backinblackcooldown.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lbl_backinblackcooldown.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_thickofitability = QLabel(self.centralwidget)
        self.lbl_thickofitability.setObjectName(u"lbl_thickofitability")
        self.lbl_thickofitability.setGeometry(QRect(570, 880, 51, 51))
        self.lbl_thickofitability.setPixmap(QPixmap(u"../images/thickofit.jpg"))
        self.lbl_thickofitability.setScaledContents(True)
        self.lbl_thickofitcooldown = QLabel(self.centralwidget)
        self.lbl_thickofitcooldown.setObjectName(u"lbl_thickofitcooldown")
        self.lbl_thickofitcooldown.setGeometry(QRect(570, 880, 51, 51))
        self.lbl_thickofitcooldown.setFont(font2)
        self.lbl_thickofitcooldown.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lbl_thickofitcooldown.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_imstillstandingability = QLabel(self.centralwidget)
        self.lbl_imstillstandingability.setObjectName(u"lbl_imstillstandingability")
        self.lbl_imstillstandingability.setGeometry(QRect(630, 880, 51, 51))
        self.lbl_imstillstandingability.setPixmap(QPixmap(u"../images/imstillstanding.jpg"))
        self.lbl_imstillstandingability.setScaledContents(True)
        self.lbl_imstillstandingcooldown = QLabel(self.centralwidget)
        self.lbl_imstillstandingcooldown.setObjectName(u"lbl_imstillstandingcooldown")
        self.lbl_imstillstandingcooldown.setGeometry(QRect(630, 880, 51, 51))
        self.lbl_imstillstandingcooldown.setFont(font2)
        self.lbl_imstillstandingcooldown.setStyleSheet(u"")
        self.lbl_imstillstandingcooldown.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.btn_resume = QPushButton(self.centralwidget)
        self.btn_resume.setObjectName(u"btn_resume")
        self.btn_resume.setGeometry(QRect(590, 310, 311, 121))
        self.btn_resume.setFont(font3)
        self.btn_resume.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_resume.setStyleSheet(u"background-color: rgb(0, 170, 255);")
        self.btn_title = QPushButton(self.centralwidget)
        self.btn_title.setObjectName(u"btn_title")
        self.btn_title.setGeometry(QRect(590, 440, 311, 121))
        self.btn_title.setFont(font3)
        self.btn_title.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_title.setStyleSheet(u"background-color: rgb(0, 170, 255);")
        self.btn_exit = QPushButton(self.centralwidget)
        self.btn_exit.setObjectName(u"btn_exit")
        self.btn_exit.setGeometry(QRect(590, 570, 311, 121))
        self.btn_exit.setFont(font3)
        self.btn_exit.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.btn_exit.setStyleSheet(u"background-color: rgb(0, 170, 255);")
        self.lbl_titlename = QLabel(self.centralwidget)
        self.lbl_titlename.setObjectName(u"lbl_titlename")
        self.lbl_titlename.setGeometry(QRect(600, 530, 291, 21))
        self.lbl_titlename.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_sixhundredstrikeability = QLabel(self.centralwidget)
        self.lbl_sixhundredstrikeability.setObjectName(u"lbl_sixhundredstrikeability")
        self.lbl_sixhundredstrikeability.setGeometry(QRect(690, 880, 51, 51))
        self.lbl_sixhundredstrikeability.setPixmap(QPixmap(u"../images/sixhundredstrike.jpg"))
        self.lbl_sixhundredstrikeability.setScaledContents(True)
        self.lbl_sixhundredstrikecooldown = QLabel(self.centralwidget)
        self.lbl_sixhundredstrikecooldown.setObjectName(u"lbl_sixhundredstrikecooldown")
        self.lbl_sixhundredstrikecooldown.setGeometry(QRect(690, 880, 51, 51))
        self.lbl_sixhundredstrikecooldown.setFont(font2)
        self.lbl_sixhundredstrikecooldown.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lbl_sixhundredstrikecooldown.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.lbl_backround.raise_()
        self.lbl_player.raise_()
        self.lst_slot_1.raise_()
        self.lst_slot_2.raise_()
        self.lst_slot_3.raise_()
        self.lst_slot_4.raise_()
        self.lst_slot_5.raise_()
        self.lst_slot_trash.raise_()
        self.lst_slot_song1.raise_()
        self.lst_slot_song2.raise_()
        self.lst_slot_song3.raise_()
        self.lst_slot_melee.raise_()
        self.lst_slot_ranged.raise_()
        self.lbl_weapon_1.raise_()
        self.lbl_weapon_2.raise_()
        self.lbl_weapon_8.raise_()
        self.lbl_weapon_7.raise_()
        self.lbl_weapon_6.raise_()
        self.lbl_weapon_3.raise_()
        self.lbl_weapon_4.raise_()
        self.lbl_weapon_5.raise_()
        self.lbl_healthbarbg.raise_()
        self.lbl_healthbar.raise_()
        self.lbl_heartnobg.raise_()
        self.lbl_playerhealth.raise_()
        self.lst_slot_armor.raise_()
        self.lbl_bowability.raise_()
        self.lbl_bowcooldown.raise_()
        self.lbl_wavename.raise_()
        self.lbl_wave.raise_()
        self.lbl_wavename_2.raise_()
        self.lbl_scorename.raise_()
        self.lbl_score.raise_()
        self.lbl_yapyapyap.raise_()
        self.lbl_bosshealthbarbg.raise_()
        self.lbl_bosshealthbar.raise_()
        self.lbl_bossheartnobg.raise_()
        self.lbl_bosshealth.raise_()
        self.lbl_bossname.raise_()
        self.lst_slot_boots.raise_()
        self.lst_slot_lifeforce.raise_()
        self.lbl_choice1_backround.raise_()
        self.lbl_choice1_title.raise_()
        self.lbl_choice1_image.raise_()
        self.lbl_choice1_description.raise_()
        self.btn_choice1.raise_()
        self.lbl_melee.raise_()
        self.lbl_ranged.raise_()
        self.lbl_armor.raise_()
        self.lbl_boots.raise_()
        self.lbl_lifeforce.raise_()
        self.lbl_disc1.raise_()
        self.lbl_disc2.raise_()
        self.lbl_disc3.raise_()
        self.lbl_choice2_backround.raise_()
        self.lbl_choice2_image.raise_()
        self.btn_choice2.raise_()
        self.lbl_choice2_description.raise_()
        self.lbl_choice2_title.raise_()
        self.lbl_choice3_backround.raise_()
        self.lbl_choice3_description.raise_()
        self.lbl_choice3_image.raise_()
        self.lbl_choice3_title.raise_()
        self.btn_choice3.raise_()
        self.lbl_backinblackability.raise_()
        self.lbl_backinblackcooldown.raise_()
        self.lbl_thickofitability.raise_()
        self.lbl_thickofitcooldown.raise_()
        self.lbl_imstillstandingability.raise_()
        self.lbl_imstillstandingcooldown.raise_()
        self.btn_resume.raise_()
        self.btn_title.raise_()
        self.btn_exit.raise_()
        self.lbl_titlename.raise_()
        self.lbl_sixhundredstrikeability.raise_()
        self.lbl_sixhundredstrikecooldown.raise_()

        self.retranslateUi(MainWindow)
        self.lst_slot_1.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_2.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_3.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_4.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_5.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_trash.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_song1.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_song2.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_song3.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_ranged.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_melee.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_armor.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_boots.clicked.connect(MainWindow.lst_slots_a)
        self.lst_slot_lifeforce.clicked.connect(MainWindow.lst_slots_a)
        self.btn_choice1.clicked.connect(MainWindow.btn_choice1_a)
        self.btn_choice2.clicked.connect(MainWindow.btn_choice2_a)
        self.btn_choice3.clicked.connect(MainWindow.btn_choice3_a)
        self.btn_resume.clicked.connect(MainWindow.btn_resume_a)
        self.btn_title.clicked.connect(MainWindow.btn_title_a)
        self.btn_exit.clicked.connect(MainWindow.btn_exit_a)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Resonance", None))
        self.lbl_player.setText("")
        self.lbl_backround.setText("")
        self.lbl_weapon_1.setText("")
        self.lbl_weapon_2.setText("")
        self.lbl_weapon_8.setText("")
        self.lbl_weapon_7.setText("")
        self.lbl_weapon_6.setText("")
        self.lbl_weapon_3.setText("")
        self.lbl_weapon_4.setText("")
        self.lbl_weapon_5.setText("")
        self.lbl_healthbar.setText("")
        self.lbl_healthbarbg.setText("")
        self.lbl_heartnobg.setText("")
        self.lbl_playerhealth.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.lbl_bowability.setText("")
        self.lbl_bowcooldown.setText("")
        self.lbl_wavename.setText(QCoreApplication.translate("MainWindow", u"Wave:", None))
        self.lbl_wave.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lbl_wavename_2.setText(QCoreApplication.translate("MainWindow", u"/10", None))
        self.lbl_scorename.setText(QCoreApplication.translate("MainWindow", u"Score:", None))
        self.lbl_score.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lbl_yapyapyap.setText("")
        self.lbl_bosshealthbar.setText("")
        self.lbl_bossheartnobg.setText("")
        self.lbl_bosshealth.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.lbl_bosshealthbarbg.setText("")
        self.lbl_bossname.setText("")
        self.lbl_choice1_backround.setText("")
        self.lbl_choice1_title.setText(QCoreApplication.translate("MainWindow", u"Sword", None))
        self.lbl_choice1_image.setText("")
        self.lbl_choice1_description.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.btn_choice1.setText(QCoreApplication.translate("MainWindow", u"Choose", None))
        self.lbl_choice2_backround.setText("")
        self.lbl_choice2_title.setText(QCoreApplication.translate("MainWindow", u"Sword", None))
        self.btn_choice2.setText(QCoreApplication.translate("MainWindow", u"Choose", None))
        self.lbl_choice2_description.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.lbl_choice2_image.setText("")
        self.lbl_choice3_backround.setText("")
        self.lbl_choice3_title.setText(QCoreApplication.translate("MainWindow", u"Sword", None))
        self.btn_choice3.setText(QCoreApplication.translate("MainWindow", u"Choose", None))
        self.lbl_choice3_description.setText(QCoreApplication.translate("MainWindow", u"Description", None))
        self.lbl_choice3_image.setText("")
        self.lbl_melee.setText(QCoreApplication.translate("MainWindow", u"Sword", None))
        self.lbl_ranged.setText(QCoreApplication.translate("MainWindow", u"Bow", None))
        self.lbl_armor.setText(QCoreApplication.translate("MainWindow", u"Armor", None))
        self.lbl_boots.setText(QCoreApplication.translate("MainWindow", u"Boots", None))
        self.lbl_lifeforce.setText(QCoreApplication.translate("MainWindow", u"Lifeforce", None))
        self.lbl_disc1.setText(QCoreApplication.translate("MainWindow", u"Disc 1", None))
        self.lbl_disc2.setText(QCoreApplication.translate("MainWindow", u"Disc 2", None))
        self.lbl_disc3.setText(QCoreApplication.translate("MainWindow", u"Disc 3", None))
        self.lbl_backinblackability.setText("")
        self.lbl_backinblackcooldown.setText("")
        self.lbl_thickofitability.setText("")
        self.lbl_thickofitcooldown.setText("")
        self.lbl_imstillstandingability.setText("")
        self.lbl_imstillstandingcooldown.setText("")
        self.btn_resume.setText(QCoreApplication.translate("MainWindow", u"Resume", None))
        self.btn_title.setText(QCoreApplication.translate("MainWindow", u"Title", None))
        self.btn_exit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.lbl_titlename.setText(QCoreApplication.translate("MainWindow", u"WARNING: RESETS PROGRESS", None))
        self.lbl_sixhundredstrikeability.setText("")
        self.lbl_sixhundredstrikecooldown.setText("")
    # retranslateUi

